server:
  port: 8081
  servlet:
    context-path: /
spring:
  data:
    elasticsearch:
    #es集群名字，查看es配置文件可以知道
      cluster-name: hz-elasticsearch
      cluster-nodes: 127.0.0.1:9300
      repositories:
        enabled: true
